name: ⚡️ Video CompressorX ⚡️

on:
  schedule:
    - cron: "0 */20000 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🐍 Set up Python 3.9 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 🌀 Clone the Repo 🌀
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_NAME }}
      - name: 📀 Install dependencies. 📀
        run: |
          pip install aiohttp python-decouple pyaesni https://github.com/1Danish-00/Telethon/archive/master.zip html_telegraph_poster requests
      - name: 🏃‍♂️ Run the UserClient. 🏃‍♂️
        run: |
          python3 start.py
